# Generated by Django 3.2.13 on 2022-04-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220420_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
